export const SET_WORDS = 'SET_TEXTBOOK_WORDS';
export const SET_GROUP = 'SET_TEXTBOOK_GROUP';
export const SET_PAGE = 'SET_TEXTBOOK_PAGE';
export const SET_SOUND = 'SET_TEXTBOOK_SOUND';
export const SET_ERROR = 'SET_TEXTBOOK_ERROR';
export const UPDATE_WORDS = 'UPDATE_WORDS';
export const SET_IS_PLAYING_SOUND = 'SET_IS_PLAYING_SOUND';
